### ISSUE TITLE
AttributeError: module 'socks' has no attribute 'create_connection'

### ISSUE THREAD

**Issue by JeetChaudhari** [decoxviii/karma#9]
Sorry If I am doing anything wrong, but I could not understand the following error. 
Karma was working like charm, but in another tab, I was using [v3n0m](https://github.com/v3n0m-Scanner/V3n0M-Scanner) and I selected enable tor/proxy setup which did some updates to pip packages which broke my karma setup.

Now, whenever I run I get the following error.

karma target jondoe@example.com

```
        6 C Z G K V H 4 H
        S U K A R M A W G
        T 5 R K 2 N M D 4

        decoxviii
        1.2.0

[+] starting search 
[+] 1/1 request email: jondoe@example.com 
Traceback (most recent call last):
  File "/usr/bin/karma", line 103, in <module>
    main()
  File "/usr/bin/karma", line 94, in main
    result = pwndb.search_info()
  File "/usr/lib/python3.7/site-packages/karma/core.py", line 180, in search_info
    response = self.email_request(target)
  File "/usr/lib/python3.7/site-packages/karma/core.py", line 92, in email_request
    return self.get_request(self.data)
  File "/usr/lib/python3.7/site-packages/karma/core.py", line 59, in get_request
    raise e
  File "/usr/lib/python3.7/site-packages/karma/core.py", line 46, in get_request
    req = self.session.post(self.site, data=data, timeout=(15, None))
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 79, in _new_conn
    conn = socks.create_connection(
AttributeError: module 'socks' has no attribute 'create_connection'
```

lsb_release -a
```
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.0.4
Codename:       Illyria
```

uname -a
`Linux xxx-PC 4.19.45-1-MANJARO #1 SMP PREEMPT Wed May 22 17:16:41 UTC 2019 x86_64 GNU/Linux`

Please help me fix this issue.

**Comment by decoxviii** [comment]
Hi @JeetChaudhari,

Try reinstalling the requirements (see `requirements.txt`) again. run:
```
sudo -H pip3 install -r requirements.txt --upgrade
```

**Comment by JeetChaudhari** [comment]
I tried upgrading dependencies according to the command you provided. Here is the output.

sudo -H pip3 install -r ./requirements.txt --upgrade

```
Requirement already up-to-date: pysocks in /usr/lib/python3.7/site-packages (from -r ./requirements.txt (line 1)) (1.7.0)
Requirement already up-to-date: texttable in /usr/lib/python3.7/site-packages (from -r ./requirements.txt (line 2)) (1.6.1)
Requirement already up-to-date: docopt in /usr/lib/python3.7/site-packages (from -r ./requirements.txt (line 3)) (0.6.2)
Requirement already up-to-date: requests in /usr/lib/python3.7/site-packages (from -r ./requirements.txt (line 4)) (2.22.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->-r ./requirements.txt (line 4)) (1.24.3)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests->-r ./requirements.txt (line 4)) (2019.3.9)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests->-r ./requirements.txt (line 4)) (2.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->-r ./requirements.txt (line 4)) (3.0.4)

```

After update, it still generates the same mistake. By the way, I have installed Karma using following command.

`sudo -H pip3 install git+https://github.com/decoxviii/karma.git`

Also tried upgrading using 

`sudo -H pip3 install git+https://github.com/decoxviii/karma.git --upgrade`

**Comment by decoxviii** [comment]
Please could show me the output the following command:
```
python3 -c "import sys; print(sys.path)"
```

**Comment by JeetChaudhari** [comment]
I used the commands provided by you.

`sudo -H pip3 install pysocks urllib3[socks] requests[socks] --upgrade`

```
Requirement already up-to-date: pysocks in /usr/lib/python3.7/site-packages (1.7.0)
Collecting urllib3[socks]
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
     |████████████████████████████████| 153kB 210kB/s 
Requirement already up-to-date: requests[socks] in /usr/lib/python3.7/site-packages (2.22.0)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests[socks]) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests[socks]) (2.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests[socks]) (2019.3.9)
pyportify 0.4.1 has requirement aiohttp==2.3.10, but you'll have aiohttp 3.5.4 which is incompatible.
pyportify 0.4.1 has requirement requests==2.18.4, but you'll have requests 2.22.0 which is incompatible.
pyportify 0.4.1 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.
gitem 0.8.1 has requirement requests==2.20.0, but you'll have requests 2.22.0 which is incompatible.
dockerscan 1.0.0a3 has requirement requests==2.13.0, but you'll have requests 2.22.0 which is incompatible.
Installing collected packages: urllib3
  Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed urllib3-1.25.3
```

`python3 -c "import sys; print(sys.path)"`

```
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/jeet/.local/lib/python3.7/site-packages', '/usr/lib/python3.7/site-packages', '/usr/lib/python3.7/site-packages/karma-1.2.0-py3.7.egg', '/usr/lib/python3.7/site-packages/gtk-2.0']
```

As the second command shows `/usr/lib/python3.7/site-packages` which is where it installed urllib3 I think it is able to find that module, however, there is also an entry for `/home/jeet/.local/lib/python3.7/site-packages` I am not sure which one it is using.

**Comment by JeetChaudhari** [comment]
I got rid of `/home/jeet/.local/lib/python3.7/` and it started working again. Thank you for your help.

**Comment by decoxviii** [comment]
I'm glad you could solve your problem, I'm going to close this issue.
